baseURL = "https://soldes.tole.es"
languageCode = "es-es"
title = "Soldes pour v√¥tre famile!"
theme = "hugo-shopping-product-catalogue-simple"

[Params]
description = "Soldes"
channel = "https://t.me/s/soldeszone"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5
