baseURL = "https://soldes.tole.es"
languageCode = "es-es"
title = "Soldes pour vôtre famile!"
theme = "hugo-shopping-product-catalogue-simple"

[Params]
description = "Réductions pour vous!"
channel = "https://t.me/s/soldeszone"
ga = "G-B78Y62XVYL"
yandex = ""

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]